//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplyTable
    {
        public int JobApplyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> JobApplyDataTime { get; set; }
        public Nullable<int> JobApplyStatusID { get; set; }
        public Nullable<System.DateTime> JobApplyStatusUpdateDate { get; set; }
        public string JobApplyStatusUpdateReason { get; set; }
        public Nullable<int> PostJobID { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual JobApplyStatusTable JobApplyStatusTable { get; set; }
        public virtual PostJobTable PostJobTable { get; set; }
    }
}
