//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJobTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostJobTable()
        {
            this.JobApplyTables = new HashSet<JobApplyTable>();
            this.JobRequirementTables = new HashSet<JobRequirementTable>();
        }
    
        public int PostJobID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> JobCategoryID { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> MinSalary { get; set; }
        public Nullable<int> MaxSalary { get; set; }
        public string Location { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public Nullable<int> JobNatureID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> ApplicationLastDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> JobRequirementID { get; set; }
        public Nullable<int> JobStatusID { get; set; }
    
        public virtual CompanyTable CompanyTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplyTable> JobApplyTables { get; set; }
        public virtual JobCategoryTable JobCategoryTable { get; set; }
        public virtual JobNatureTable JobNatureTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequirementTable> JobRequirementTables { get; set; }
        public virtual JobRequirementTable JobRequirementTable { get; set; }
        public virtual JobStatusTable JobStatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
